### ISSUE TITLE
USB_DEVICE directory is missing?

### ISSUE THREAD

**Issue by S2000Stefan** [grblHAL/STM32F3xx#1]
I visited the new home of grblHAL today and tried to compile my driver. 
It's not a real issues because only one directory is missing.
In any case, this compilation error occurs:

![USB_Verzeichnis](https://user-images.githubusercontent.com/35189051/111871317-8a5fef80-8989-11eb-8f7b-97ed46a7b322.jpg)

After copying the USB_DEVICE directory from an older version, the compilation is successful.
;-)

**Comment by terjeio** [comment]
Thanks, I have added the directory now.
