### ISSUE TITLE
two warnings after compile

### ISSUE THREAD

**Issue by S2000Stefan** [grblHAL/STM32F3xx#2]
Hello terjeio,

unfortunately i am very busy at the moment and have very very little time for my cnc hobby. That's why i'm very rarely here lately. I have to say that a lot has happened since I was here last time, which is nice.
Now to my concern, after I compile grblhal only with the original settings, have not changed anything in the files, for the F3 I get 2 warnings:

13:22:03 Build Finished. 0 errors, 2 warnings. (took 6s.521ms)

../USB_DEVICE/App/usbd_cdc_if.c: In function 'CDC_Receive_FS':
../USB_DEVICE/App/usbd_cdc_if.c:263:3: warning: implicit declaration of function 'usbBufferInput' [-Wimplicit-function-declaration]
   usbBufferInput(Buf, *Len)

     from ../Src/serial.c:30:
../Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_hal_def.h:58:0: warning: "UNUSED" redefined
 #define UNUSED(X) (void)X      /* To avoid gcc/g++ warnings */

Also, some changes have been made to the four-axis operation, do I have to pay attention to anything when I activate 4 axes in config.h?

greetings
Stefan

**Comment by terjeio** [comment]
@S2000Stefan Nice to hear from you again! Yes there has been a lot of changes - too much coding so not much time to spend the workshop for me as well. Every time I believe I can get a break from coding something pops up that needs attention...

The compiler warnings can be ignored, I'll fix those in the next commit.
Before you enable the fourth axis save your settings and restore them after flashing as it is likely they will be lost. Other than that I hope the build is ok.

**Comment by S2000Stefan** [comment]
Hi terjeio,
Unfortunately, I have to get back to you. After I have reactivated everything I need for my machine, there is no longer any connection to the controller.  I found out that if I #define ENABLE_SAFETY_DOOR_INPUT_PIN // Default disabled. Uncomment to enable. the error occurs. You're probably thinking, not the SAFETY_DOOR_INPUT_PIN again. :)

Plugins: Eeprom, Odometer
I have set the probe pin to B9, 4 axis enabled, #define ACCELERATION_TICKS_PER_SECOND 200, #define BLOCK_BUFFER_SIZE 156, #define SEGMENT_BUFFER_SIZE 24 all set in config.h
Until then, the controller will run normally, I have not checked the pins yet.
But then two other warnings occur:

../Src/driver.c:91:22: warning: 'probe' defined but not used [-Wunused-variable]
../Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_hal_def.h:58:0: warning: "UNUSED" redefined
19:13:42 Build Finished. 0 errors, 2 warnings. (took 3s.230ms)

As soon as i activate the saefty door pin in config.h, ioSender no longer establishes a connection.

A lot has changed with the ioSender too, you've been busy. :)
Use the latest edge version 36p10b.

greetings
Stefan

**Comment by terjeio** [comment]
I have harmonized most of the #define symbols across drivers, and I have missed one rename in this:

https://github.com/grblHAL/STM32F3xx/blob/e284ca829eb2703d53174e1c3579a4b4f00cfb11/Src/driver.c#L1109

Change it to `#ifdef SAFETY_DOOR_PIN` and recompile.

The probe warning should not occur if you have the probe pin enabled. If you are using the generic map this is disabled by default when fourth axis is enabled. You have to remove the guard around the probe definition to enable it, change:
```
#if N_ABC_MOTORS == 0
// Define probe switch input pin.
#define PROBE_PORT              GPIOB
#define PROBE_PIN               9
#endif
```
to:
```
// Define probe switch input pin.
#define PROBE_PORT              GPIOB
#define PROBE_PIN               9
```

You can verify the pin mappings with the new `$pins` command, this outputs them to the console.

**Comment by S2000Stefan** [comment]
> Change it to #ifdef SAFETY_DOOR_PIN and recompile.

After recompile now everything works as it should.
The probe warning is now also history. 
Great support as always, thank you. :+1: 

> You can verify the pin mappings with the new $pins command, this outputs them to the console.

I think I'll have to read a lot here over the next few days to get to know all the new functions. :)
One should not let the break become too big. ;)
