### ISSUE TITLE
Build 20211130, compile error

### ISSUE THREAD

**Issue by S2000Stefan** [grblHAL/STM32F3xx#3]
Hello terjeio,

Unfortunately, 3 errors are displayed when I compile.

../grbl/settings.c:509:6: error: expected '}' before '{' token
      { Setting_DoorSpindleOnDelay, Group_SafetyDoor, "Spindle on delay", "s", Format_Decimal, "#0.0", "0.5", "20", Setting_IsExtended, &settings.safety_door.spindle_on_delay, NULL, NULL },
      ^
arm-none-eabi-gcc "../grbl/tool_change.c" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F303xC -c -I../Drivers/STM32F3xx_HAL_Driver/Inc -I../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F3xx/Include -I../Drivers/CMSIS/Include -I../Inc -I"C:/grblhal_F303_16_master/STM32F3xx-master/STM32F3xx-master" -I"C:/grblhal_F303_16_master/STM32F3xx-master/STM32F3xx-master/Src" -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"grbl/tool_change.d" -MT"grbl/tool_change.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "grbl/tool_change.o"
make: *** [grbl/subdir.mk:147: grbl/settings.o] Error 1
make: *** Waiting for unfinished jobs....
"make -j12 all" terminated with exit code 2. Build might be incomplete.

15:55:25 Build Failed. 3 errors, 0 warnings. (took 1s.842ms)

As always, the 4th axis is activated and safty door is on. :-)

greetings
Stefan

**Comment by terjeio** [comment]
Oops, all because of a missing comma on the end of line 502... Enabling the safety door (or a 5th axis) triggers it.
I'll commit a fix soon - you may just add the missing comma.

Thanks for reporting,
Terje

**Comment by S2000Stefan** [comment]
Yes sometimes the pen is mightier than the sword. ;-)
You are slowly teaching me how to program.
Problem solved. :+1:
