### ISSUE TITLE
Use Arduino IDE

### ISSUE THREAD

**Issue by ghost** [grblHAL/STM32F3xx#4]
Hi terjeio,

I have been reading through the documentation on compiling the STM32F303xxx code with the Arduino IDE but I cannot install as per the instructions.

I am a relative novice at using IDE's and would greatly appreciate a little advice as I am sure I am doing something wrong.

Cheers
G

**Comment by terjeio** [comment]
The Arduino IDE is only used for the iMXRT1062, SAMD21 and SAM3X8E drivers. I have no plans to change that so your options are to use the STM32CubeIDE or possibly PlatformIO for compiling. PlatformIO will require a new platformio.ini file. I do not know if PlatformIO supports this processor.

**Comment by ghost** [comment]
OK and thanks for the information.

Cheers
G
